global_costmap:

  map_type: costmap
  track_unknown_space: true
  unknown_cost_value: 255
  obstacle_range: 2.5
  raytrace_range: 3.0
  #robot_radius: 0.20  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
  footprint: [[0.25, 0.21],
              [-0.25, 0.21],
              [-0.25, -0.21],
              [0.25, -0.21]]
  #inflation_radius: 0.32
  inflation_radius: 0.37
  #transform_tolerance: 0.5
  inscribed_radius: 0.3
  circumscribed_radius: 0.32

  global_frame: /map
  #robot_base_frame: /base_link
  robot_base_frame: /base_footprint
  update_frequency: 0.5
  publish_frequency: 0.1
  static_map: true
  rolling_window: false
  #rolling_window: true

  #Investigate what this actually does
  #cost_scaling_factor: 10.0
  cost_scaling_factor: 15.0
